### ISSUE TITLE
Miglioramento ricette di crafting

### ISSUE THREAD

**Issue by Luca255** [RAD750/gastronomod#3]
1) Al momento il "Sugo di pomodoro" in barattolo si crafta solo con un "Pentolino con sugo di pomodoro cotto". Sarebbe meglio che nella ricetta di crafting ci fosse anche un barattolo vuoto.

2) Al momento la pizza si crafta con i pomodori interi, sarebbe meglio sostituirli con il sugo

**Comment by RAD750** [comment]
1. Bug
2. Miglioramento possibile

**Comment by RAD750** [comment]
Sistemato 76165af
